//ZBE3GO   JOB (ZBRIDGE),'E3 GO BYTES SVC35',CLASS=A,MSGCLASS=A,
//             MSGLEVEL=(1,1)
//*
//* zbridge-asm-lab rung E3 - GENERATED by zbridge/cmd/gen-e3. Do not edit.
//*
//* Every byte of the parameter list below was produced by Go, by
//* zbridge/console.EncodeWPL, running on a Windows laptop, and rendered into
//* DC constants by console.FormatDC. No human wrote these bytes and IBM's WTO
//* macro was not involved.
//*
//* If the operator console displays the message, the Go-side construction of
//* the WTO parameter list is verified against a real SVC 35 - without Go ever
//* running on a mainframe. That is rung E3.
//*
//ASM      EXEC ASMFCLG,PARM.ASM='OBJ,LIST'
//ASM.SYSIN DD  *
ZBE3GO   CSECT
         SAVE  (14,12)
         LR    12,15
         USING ZBE3GO,12
*
* MVS linkage: R1 carries the parameter list address; SVC 35 is WTO.
*
         LA    1,WPL
         SVC   35
         RETURN (14,12),RC=0
*
* The Go-produced parameter list, fullword aligned.
*
         DS    0F
WPL      DC    X'00250000E9C2D9C9C4C7C540E3C5E2E3'
         DC    X'40C5F340C2E8E3C5E240C2E4C9D3E340'
         DC    X'C2E840C7D6'
         END
/*
