package console

import (
	"encoding/binary"
	"fmt"
	"strings"

	"github.com/mertefesensoy/zbridge"
	"github.com/mertefesensoy/zbridge/codepage"
)

// ---------------------------------------------------------------------------
// The WTO parameter list layout
// ---------------------------------------------------------------------------
//
// Verified 2026-07-26 by assembling `WTO 'text',MF=L` under IFOX00 (Assembler XF)
// on MVS 3.8j (TK5 Update 5) with PRINT ON,GEN,DATA, and reading the listing.
// Evidence: docs/evidence/E1-wto-macro-expansion-2026-07-26.md
//
// This is a macro expansion, not a manual quotation, and that is deliberate:
// research brief 003 Q1 established that the layout is not documented in prose in
// the MVS 3.8j supervisor manual at all, and Q6 established that no IBM
// publication prints the generated expansion — PRINT GEN is the authoritative
// instrument. So the assembler listing IS the primary source.
//
// The listing, for a minimal single-line WTO with an 18-character message:
//
//	LOC    OBJECT CODE          SOURCE
//	000000                      WPLMIN  DC 0F'0'                     <- fullword align
//	000000 0016                          DC AL2(22)   TEXT LENGTH
//	000002 0000                          DC B'0...0'  MCS FLAGS
//	000004 E9C2D9C9C4C7C540              DC C'ZBRIDGE TEST HELLO'
//	00000C E3C5E2E340C8C5D3
//	000014 D3D6
//
//	 byte:  0     1     2     3     4                             n+4
//	       +-----------+-----------+-------------------------------+
//	       |  length   | MCS flags |   message text (EBCDIC)       |
//	       +-----------+-----------+-------------------------------+
//	       |<- big-endian halfword, value = len(text) + 4
//
// Two lengths were checked, which is what makes the "+4" a rule rather than a
// coincidence: an 18-character message gave 0x0016 (22) and a 38-character
// message gave 0x002A (42).
//
// The +4 is self-explanatory once the layout is visible: the length field counts
// its own 2 bytes plus the 2 flag bytes plus the text. It is a length of the
// *parameter list header plus text*, not a length of the text.
//
// # Why only the minimal form is implemented
//
// The same listing also revealed the routed form, and it holds a trap:
//
//	000018 0016   DC AL2(22)                TEXT LENGTH      <- still 22!
//	00001A 8000   DC B'1000000000000000'    MCS FLAGS        <- bit 0 set
//	00001C ...    DC C'ZBRIDGE TEST HELLO'  MESSAGE TEXT
//	00002E 0200   DC B'0000001000000000'    DESCRIPTOR CODES
//	000030 0020   DC B'0000000000100000'    ROUTING CODES
//
// MCS flag bit 0 (0x8000) signals that descriptor and routing halfwords follow
// the text — and **the length field still reads 22**, so it does not cover them.
// An implementation that assumed "length = whole parameter list" would be wrong
// in a way that only shows up when routing codes are used.
//
// That form is NOT implemented here, on the owner's decision (2026-07-26), for
// one reason: research brief 003 Q3 is NOT FOUND — there is no citable
// bit-by-bit table of the MCS flags, so whether z/OS assigns the other bits the
// same way is unknown. WithRoute and WithDescriptor therefore still return
// ErrLayoutUnverified. See ADR 0003 §4.
const (
	// wplLengthOff is the offset of the 2-byte big-endian length field.
	wplLengthOff = 0

	// wplFlagsOff is the offset of the 2-byte MCS flags field.
	wplFlagsOff = 2

	// wplTextOff is the offset at which the EBCDIC message text begins, and
	// therefore also the number of header bytes the length field counts in
	// addition to the text.
	wplTextOff = 4

	// wplMinFlags is the MCS flags value for a minimal single-line WTO with no
	// routing or descriptor codes: all bits zero, as generated by the macro.
	wplMinFlags = 0x0000
)

// LayoutVerified reports whether the WPL byte layout has a primary-source
// citation.
//
// It became true on 2026-07-26 when the layout was read out of IBM's own macro
// expansion on MVS 3.8j. It covers the **minimal single-line form only**.
const LayoutVerified = true

// LayoutStatus describes the documentary basis for the layout this package uses.
const LayoutStatus = "VERIFIED (minimal single-line form) from the IFOX00 assembler expansion of " +
	"WTO 'text',MF=L on MVS 3.8j TK5 Update 5, 2026-07-26 — see " +
	"docs/evidence/E1-wto-macro-expansion-2026-07-26.md. Layout: bytes 0-1 big-endian " +
	"length = len(text)+4, bytes 2-3 MCS flags, byte 4+ EBCDIC text, fullword-aligned. " +
	"The routed form (MCS flag 0x8000 with descriptor and routing halfwords appended " +
	"after the text) is observed but NOT implemented: brief 003 Q3 found no citable " +
	"MCS bit table, so z/OS bit assignments are unconfirmed."

// EncodeWPL builds the WTO parameter list for msg and returns it as bytes ready
// to be pointed at by R1.
//
// It is pure Go and runs on any host, by design. Rung E3 of the project's
// evidence ladder verifies the Go-side parameter-list construction by embedding
// this function's output in an MVS assembler program as DC X'...' constants and
// handing it to a real SVC 35 — so this function's output is the artifact of that
// rung, not an implementation detail. See ADR 0003 §6.
//
// # Alignment is the caller's responsibility
//
// The macro emits `DC 0F'0'` before the list, so the parameter list must be
// fullword-aligned. A Go []byte carries no alignment guarantee, so the returned
// slice is a *value*, not a usable parameter list address. On z/OS the bytes must
// be copied into fullword-aligned storage below the bar — internal/storage's job
// — before R1 is pointed at them.
//
// # Routing and descriptor codes are rejected, not ignored
//
// Passing WithRoute or WithDescriptor returns ErrLayoutUnverified rather than
// silently producing a list without them. Dropping caller-requested routing
// would send an operator message somewhere the caller did not ask for.
func EncodeWPL(msg string, opts ...Option) ([]byte, error) {
	const op = "console.EncodeWPL"

	if err := validate(msg); err != nil {
		return nil, err
	}

	o := resolve(opts)
	if len(o.routes) > 0 || len(o.descriptors) > 0 {
		// The routed form is observed in the macro expansion but its MCS bit
		// assignments are not citable for z/OS (brief 003 Q3). Refusing beats
		// guessing, and beats silently dropping the request.
		return nil, zbridge.Unverified(op, "SVC 35", "U2")
	}

	buf := make([]byte, wplTextOff+len(msg))

	// Bytes 0-1: big-endian length = len(text) + 4. The field counts the two
	// length bytes and the two flag bytes as well as the text.
	binary.BigEndian.PutUint16(buf[wplLengthOff:], uint16(len(msg)+wplTextOff))

	// Bytes 2-3: MCS flags. Zero for a minimal single-line WTO.
	binary.BigEndian.PutUint16(buf[wplFlagsOff:], wplMinFlags)

	// Bytes 4+: the message text, converted to EBCDIC IBM-1047.
	codepage.AtoE(buf[wplTextOff:], []byte(msg))

	return buf, nil
}

// validate applies the checks that do not depend on the layout.
func validate(msg string) error {
	const op = "console.EncodeWPL"

	if len(msg) == 0 {
		return &zbridge.Error{
			Op:      op,
			Service: "SVC 35",
			Err:     fmt.Errorf("empty message"),
		}
	}
	if len(msg) > MaxTextLen {
		return &zbridge.Error{
			Op:      op,
			Service: "SVC 35",
			Err:     zbridge.ErrMessageTooLong,
		}
	}
	// A console is an operator's workplace. Control characters in an operator
	// message are at best noise and at worst confusing on a 3270.
	for i := 0; i < len(msg); i++ {
		if msg[i] < 0x20 || msg[i] == 0x7F {
			return &zbridge.Error{
				Op:      op,
				Service: "SVC 35",
				Err:     fmt.Errorf("message contains control byte 0x%02X at offset %d", msg[i], i),
			}
		}
	}
	return nil
}

// FormatDC renders bytes as an MVS assembler DC constant, wrapped to fit a
// fixed-form assembler source line.
//
// This is the other half of the E3 seam. The output is pasted directly into an
// assembler program that is then submitted to the emulated system, so the Go
// side of rung E3 is EncodeWPL followed by FormatDC and nothing else.
func FormatDC(label string, b []byte) string {
	const bytesPerLine = 16

	var sb strings.Builder
	for i := 0; i < len(b); i += bytesPerLine {
		end := i + bytesPerLine
		if end > len(b) {
			end = len(b)
		}

		name := ""
		if i == 0 {
			name = label
		}

		var hex strings.Builder
		for _, c := range b[i:end] {
			fmt.Fprintf(&hex, "%02X", c)
		}

		fmt.Fprintf(&sb, "%-8s DC    X'%s'\n", name, hex.String())
	}
	return sb.String()
}
