// Command gen-e3 emits the rung E3 job: an MVS assembler program whose WTO
// parameter list is the byte sequence GO produced, embedded as DC X'...'
// constants and handed to a real SVC 35.
//
// This is the E3 seam made executable (ADR 0003 §6). Go never runs on the
// mainframe; its BYTES cross. If the operator console displays the message, the
// Go-side construction of the WTO parameter list is verified against a genuine
// SVC 35 implementation.
//
// Usage:
//
//	go run ./cmd/gen-e3 [message] > zbe3go.jcl
//
// The generated job is submitted through the socket card reader; see
// docs/runbooks/tk5-hercules-setup.md §12.
package main

import (
	"fmt"
	"os"

	"github.com/mertefesensoy/zbridge/console"
)

const defaultMsg = "ZBRIDGE TEST E3 BYTES BUILT BY GO"

func main() {
	msg := defaultMsg
	if len(os.Args) > 1 {
		msg = os.Args[1]
	}

	wpl, err := console.EncodeWPL(msg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "EncodeWPL: %v\n", err)
		os.Exit(1)
	}

	// Diagnostics go to stderr so stdout stays pure JCL.
	fmt.Fprintf(os.Stderr, "message      : %q (%d chars)\n", msg, len(msg))
	fmt.Fprintf(os.Stderr, "WPL bytes    : % X\n", wpl)
	fmt.Fprintf(os.Stderr, "length field : %d = len(text) %d + 4\n",
		int(wpl[0])<<8|int(wpl[1]), len(msg))
	fmt.Fprintf(os.Stderr, "MCS flags    : %02X %02X\n", wpl[2], wpl[3])
	fmt.Fprintf(os.Stderr, "layout       : %s\n", console.LayoutStatus)

	// The programmer-name field on a JOB card is limited to 20 characters on
	// MVS 3.8j. Exceeding it gives IEF642I EXCESSIVE PARAMETER LENGTH ON THE
	// JOB STATEMENT and the job is not run at all — learned the hard way on
	// 2026-07-26 with a 22-character name.
	fmt.Print(`//ZBE3GO   JOB (ZBRIDGE),'E3 GO BYTES SVC35',CLASS=A,MSGCLASS=A,
//             MSGLEVEL=(1,1)
//*
//* zbridge-asm-lab rung E3 - GENERATED by zbridge/cmd/gen-e3. Do not edit.
//*
//* Every byte of the parameter list below was produced by Go, by
//* zbridge/console.EncodeWPL, running on a Windows laptop, and rendered into
//* DC constants by console.FormatDC. No human wrote these bytes and IBM's WTO
//* macro was not involved.
//*
//* If the operator console displays the message, the Go-side construction of
//* the WTO parameter list is verified against a real SVC 35 - without Go ever
//* running on a mainframe. That is rung E3.
//*
//ASM      EXEC ASMFCLG,PARM.ASM='OBJ,LIST'
//ASM.SYSIN DD  *
ZBE3GO   CSECT
         SAVE  (14,12)
         LR    12,15
         USING ZBE3GO,12
*
* MVS linkage: R1 carries the parameter list address; SVC 35 is WTO.
*
         LA    1,WPL
         SVC   35
         RETURN (14,12),RC=0
*
* The Go-produced parameter list, fullword aligned.
*
         DS    0F
`)
	fmt.Print(console.FormatDC("WPL", wpl))
	fmt.Print("         END\n/*\n")
}
